site_name: Data Visualization

nav:
  - Home: index.md
  - Contributing: CONTRIBUTING.md
  - Heatmaps (IPyMarkdown): temp.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  icon:
    admonition:
      python: fontawesome/solid/code
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  name: material
  custom_dir: overrides

  features:
    - header.autohide
    - navigation.tabs
    - navigation.footer
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

plugins:
  - termynal
  - search
  - tags:
      tags_file: tags.md
  - git-authors:
      show_contribution: true
      show_line_count: true
      show_email_address: true
      count_empty_lines: true
      fallback_to_empty: false
      sort_authors_by: name
      authorship_threshold_percent: 10
      exclude:
        - index.md
      enabled: true

extra:
  analytics:
    provider: google
    property: G-XXXXXXX

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Mukhopadhyay
      name: Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/praneshmukhopadhyay/
      name: Linkedin
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/allthingstensor
      name: Twitter / X

copyright: Copyright &copy; 2020 - 2023 Pranesh Mukhopadhyay
