site_name: Data Visualization

nav:
    - Home: index.md
    - Contributing: CONTRIBUTING.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  name: material

  # features:
  #   - navigation.tabs

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        # icon: material/lightbulb
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        # icon: material/lightbulb-outline
        icon: material/brightness-7
        name: Switch to light mode

plugins:
  - termynal
  - search
  - git-authors:
      show_contribution: true
      show_line_count: true
      show_email_address: true
      count_empty_lines: true
      fallback_to_empty: false
      sort_authors_by: name
      authorship_threshold_percent: 10
      exclude:
          - index.md
      enabled: true
